### ISSUE TITLE
Request supported Thai Language

### ISSUE THREAD

**Issue by mp3wizard** [dcasia/figma-plugin-font-mixer#1]
Do I have hope? ^_^

**For more information**
Range | U+0E00..U+0E7F (128 code points)
UNICODE range for Thai Language: https://jrgraphix.net/r/Unicode/0E00-0E7F

**Comment by ItsRyanWu** [comment]
@mp3wizard 
Sure you have. I have already released a new version for it on GitHub and hope it will get approved by Figma official asap.
Feel free to open other issues/suggestions here.
